export const SET_RATES_CRYPTO = 'RATE/SET_RATES_CRYPTO';
export const SET_RATES_CURRENCY = 'RATE/SET_RATES_CURRENCY';
export const SET_CURRENCY_PRICES = 'RATE/SET_CURRENCY_PRICES';
export const SELECT_CRYPTO = 'RATE/SELECT_CRYPTO';
export const GET_NEW_CRYPTO_CURRENCY = 'RATE/GET_NEW_CRYPTO_CURRENCY';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_LOADER = 'APP/SHOW_LOADER';